spring:
  datasource:
    url: jdbc:derby:memory:local;create=true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8042 # Use a unique port, for running on a single deployment server

# This is the secret key used for signing JWT tokens. In production, you MUST move this to an environment file
# which is NOT stored in GIT!
jwt_secret_key: WouldAWoodchuckChuckIfARoundhouseKick
