spring:
  datasource:
    url: jdbc:derby:memory:local;create=true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  # Disable caching of Thymeleaf templates (refresh browser without restarting server)
  thymeleaf:
    cache: false

  # Disable static file caching
  web:
    resources:
      chain:
        cache: false
      static-locations: file:src/main/resources/static

